### PR TITLE
Fix incorrect `apple-touch-icon` link

### PR DESCRIPTION
**Pull request by santiagorodriguez96**
## Summary

We were getting some 404s given that we were referencing a file that does not exist. This PR changes it so that we actually add a valid `apple-touch-icon.png` and `apple-touch-icon-precomposed.png` so that no iOS device will cause a 404s when trying to request the icon.

Though the dimensions of the icon can vary between iOS devices, including a link tag with a `sizes` of `180x180` in the `<head>` of the page is enough to to cover all of the devices.

Worth noting that the icon looks good now even before this change – it's probably fetching the icon from the favicon or something – and removing the link does not change that but it will generate a lot of 404s.

I tested this using my local setup and I'm not getting any more `404s` when clink on the iOS `share` button and `Add to home screen`.

References:

* https://github.com/h5bp/html5-boilerplate/blob/29d7d80/docs/extend.md#apple-touch-icons
* https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html
* https://mathiasbynens.be/notes/touch-icons

### CODE REVIEW

**Review by EmilioCristalli — APPROVED** [review]
I wonder if we should use the asset pipeline for these images (put them in /app/assets/images and then use `image_url('apple-touch-icon-precomposed.png')`, like we do with the `og:image` below). I guess the benefit would be the asset pipeline adds some kind of hash to the name to avoid issues with cached assets if we ever change the image.

But i think this is good enough anyway

**Comment by santiagorodriguez96** [comment]
> I wonder if we should use the asset pipeline for these images (put them in /app/assets/images and then use `image_url('apple-touch-icon-precomposed.png')`, like we do with the `og:image` below). I guess the benefit would be the asset pipeline adds some kind of hash to the name to avoid issues with cached assets if we ever change the image.
> 
> But i think this is good enough anyway

Yeah, that might work too! I thought the `apple-touch-icon.png` in the root of the application was needed first, but then I was able to make it work with the `href` in the header so we might be able to just remove it. Let me check 🙂

**Comment by santiagorodriguez96** [comment]
> > I wonder if we should use the asset pipeline for these images (put them in /app/assets/images and then use `image_url('apple-touch-icon-precomposed.png')`, like we do with the `og:image` below). I guess the benefit would be the asset pipeline adds some kind of hash to the name to avoid issues with cached assets if we ever change the image.
> > But i think this is good enough anyway
> 
> Yeah, that might work too! I thought the `apple-touch-icon.png` in the root of the application was needed first, but then I was able to make it work with the `href` in the header so we might be able to just remove it. Let me check 🙂

Hmmm unfortunately I started to get 404s again when clicking on the `share` button after removing the `apple-touch-icon.png` 🙃

**Comment by EmilioCristalli** [comment]
ok, let's merge as-is then

**Pull request merged**
